/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// VolumeAPIService VolumeAPI service
type VolumeAPIService service

// --- refreshVolume ---

type ApiRefreshVolumeRequest struct {
	ctx        context.Context
	ApiService *VolumeAPIService
	volumeId   string
	body       *map[string]interface{}
}

func (r ApiRefreshVolumeRequest) Body(body map[string]interface{}) ApiRefreshVolumeRequest {
	r.body = &body
	return r
}

func (r ApiRefreshVolumeRequest) Execute() (*http.Response, error) {
	return r.ApiService.RefreshVolumeExecute(r)
}

/*
RefreshVolume Refresh volume

Refreshes volume metadata and statistics from the array

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc.
	@param volumeId Volume ID
	@return ApiRefreshVolumeRequest
*/
func (a *VolumeAPIService) RefreshVolume(ctx context.Context, volumeId string) ApiRefreshVolumeRequest {
	return ApiRefreshVolumeRequest{
		ApiService: a,
		ctx:        ctx,
		volumeId:   volumeId,
	}
}

func (a *VolumeAPIService) RefreshVolumeExecute(r ApiRefreshVolumeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VolumeAPIService.RefreshVolume")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/instances/Volume::{volumeId}/action/refreshVolume"
	localVarPath = strings.Replace(localVarPath, "{"+"volumeId"+"}", url.PathEscape(parameterValueToString(r.volumeId, "volumeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return nil, reportError("body is required and must be specified")
	}

	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// --- restoreVolume ---

type ApiRestoreVolumeRequest struct {
	ctx                  context.Context
	ApiService           *VolumeAPIService
	volumeId             string
	restoreVolumePayload *RestoreVolumePayload
}

func (r ApiRestoreVolumeRequest) RestoreVolumePayload(restoreVolumePayload RestoreVolumePayload) ApiRestoreVolumeRequest {
	r.restoreVolumePayload = &restoreVolumePayload
	return r
}

func (r ApiRestoreVolumeRequest) Execute() (*http.Response, error) {
	return r.ApiService.RestoreVolumeExecute(r)
}

/*
RestoreVolume Restore volume from snapshot

Restores volume from a snapshot

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc.
	@param volumeId Volume ID
	@return ApiRestoreVolumeRequest
*/
func (a *VolumeAPIService) RestoreVolume(ctx context.Context, volumeId string) ApiRestoreVolumeRequest {
	return ApiRestoreVolumeRequest{
		ApiService: a,
		ctx:        ctx,
		volumeId:   volumeId,
	}
}

func (a *VolumeAPIService) RestoreVolumeExecute(r ApiRestoreVolumeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VolumeAPIService.RestoreVolume")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/instances/Volume::{volumeId}/action/restoreVolume"
	localVarPath = strings.Replace(localVarPath, "{"+"volumeId"+"}", url.PathEscape(parameterValueToString(r.volumeId, "volumeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.restoreVolumePayload == nil {
		return nil, reportError("restoreVolumePayload is required and must be specified")
	}

	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarPostBody = r.restoreVolumePayload
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// --- mapVolumeToHost ---

type ApiMapVolumeToHostRequest struct {
	ctx                    context.Context
	ApiService             *VolumeAPIService
	volumeId               string
	mapVolumeToHostPayload *MapVolumeToHostPayload
}

func (r ApiMapVolumeToHostRequest) MapVolumeToHostPayload(mapVolumeToHostPayload MapVolumeToHostPayload) ApiMapVolumeToHostRequest {
	r.mapVolumeToHostPayload = &mapVolumeToHostPayload
	return r
}

func (r ApiMapVolumeToHostRequest) Execute() (*http.Response, error) {
	return r.ApiService.MapVolumeToHostExecute(r)
}

/*
MapVolumeToHost Map volume to host

Maps a volume to an NVMe host with specified access mode

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc.
	@param volumeId Volume ID
	@return ApiMapVolumeToHostRequest
*/
func (a *VolumeAPIService) MapVolumeToHost(ctx context.Context, volumeId string) ApiMapVolumeToHostRequest {
	return ApiMapVolumeToHostRequest{
		ApiService: a,
		ctx:        ctx,
		volumeId:   volumeId,
	}
}

func (a *VolumeAPIService) MapVolumeToHostExecute(r ApiMapVolumeToHostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VolumeAPIService.MapVolumeToHost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/instances/Volume::{volumeId}/action/addMappedHost"
	localVarPath = strings.Replace(localVarPath, "{"+"volumeId"+"}", url.PathEscape(parameterValueToString(r.volumeId, "volumeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.mapVolumeToHostPayload == nil {
		return nil, reportError("mapVolumeToHostPayload is required and must be specified")
	}

	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarPostBody = r.mapVolumeToHostPayload
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// --- unmapVolumeFromHost ---

type ApiUnmapVolumeFromHostRequest struct {
	ctx                        context.Context
	ApiService                 *VolumeAPIService
	volumeId                   string
	unmapVolumeFromHostPayload *UnmapVolumeFromHostPayload
}

func (r ApiUnmapVolumeFromHostRequest) UnmapVolumeFromHostPayload(unmapVolumeFromHostPayload UnmapVolumeFromHostPayload) ApiUnmapVolumeFromHostRequest {
	r.unmapVolumeFromHostPayload = &unmapVolumeFromHostPayload
	return r
}

func (r ApiUnmapVolumeFromHostRequest) Execute() (*http.Response, error) {
	return r.ApiService.UnmapVolumeFromHostExecute(r)
}

/*
UnmapVolumeFromHost Unmap volume from host

Unmaps a volume from an NVMe host

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc.
	@param volumeId Volume ID
	@return ApiUnmapVolumeFromHostRequest
*/
func (a *VolumeAPIService) UnmapVolumeFromHost(ctx context.Context, volumeId string) ApiUnmapVolumeFromHostRequest {
	return ApiUnmapVolumeFromHostRequest{
		ApiService: a,
		ctx:        ctx,
		volumeId:   volumeId,
	}
}

func (a *VolumeAPIService) UnmapVolumeFromHostExecute(r ApiUnmapVolumeFromHostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VolumeAPIService.UnmapVolumeFromHost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/instances/Volume::{volumeId}/action/removeMappedHost"
	localVarPath = strings.Replace(localVarPath, "{"+"volumeId"+"}", url.PathEscape(parameterValueToString(r.volumeId, "volumeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.unmapVolumeFromHostPayload == nil {
		return nil, reportError("unmapVolumeFromHostPayload is required and must be specified")
	}

	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	localVarHTTPHeaderAccepts := []string{}
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarPostBody = r.unmapVolumeFromHostPayload
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
