/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// StoragePoolAPIService StoragePoolAPI service
type StoragePoolAPIService service

type ApiCreateStoragePoolGen2Request struct {
	ctx                  context.Context
	ApiService           *StoragePoolAPIService
	storagePoolParamGen2 *StoragePoolParamGen2
}

func (r ApiCreateStoragePoolGen2Request) StoragePoolParamGen2(storagePoolParamGen2 StoragePoolParamGen2) ApiCreateStoragePoolGen2Request {
	r.storagePoolParamGen2 = &storagePoolParamGen2
	return r
}

func (r ApiCreateStoragePoolGen2Request) Execute() (*StoragePoolResp, *http.Response, error) {
	return r.ApiService.CreateStoragePoolGen2Execute(r)
}

/*
CreateStoragePoolGen2 Create storage pool (Gen2 with EC support)

Creates a storage pool with Erasure Coding support

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateStoragePoolGen2Request
*/
func (a *StoragePoolAPIService) CreateStoragePoolGen2(ctx context.Context) ApiCreateStoragePoolGen2Request {
	return ApiCreateStoragePoolGen2Request{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return StoragePoolResp
func (a *StoragePoolAPIService) CreateStoragePoolGen2Execute(r ApiCreateStoragePoolGen2Request) (*StoragePoolResp, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *StoragePoolResp
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StoragePoolAPIService.CreateStoragePoolGen2")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/types/StoragePool/instances"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.storagePoolParamGen2 == nil {
		return localVarReturnValue, nil, reportError("storagePoolParamGen2 is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.storagePoolParamGen2
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiSetErasureCodingPolicyRequest struct {
	ctx                    context.Context
	ApiService             *StoragePoolAPIService
	poolId                 string
	setErasureCodingPolicy *SetErasureCodingPolicy
}

func (r ApiSetErasureCodingPolicyRequest) SetErasureCodingPolicy(setErasureCodingPolicy SetErasureCodingPolicy) ApiSetErasureCodingPolicyRequest {
	r.setErasureCodingPolicy = &setErasureCodingPolicy
	return r
}

func (r ApiSetErasureCodingPolicyRequest) Execute() (*http.Response, error) {
	return r.ApiService.SetErasureCodingPolicyExecute(r)
}

/*
SetErasureCodingPolicy Set Erasure Coding policy

Sets the Erasure Coding policy on a storage pool

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param poolId Storage Pool ID
	@return ApiSetErasureCodingPolicyRequest
*/
func (a *StoragePoolAPIService) SetErasureCodingPolicy(ctx context.Context, poolId string) ApiSetErasureCodingPolicyRequest {
	return ApiSetErasureCodingPolicyRequest{
		ApiService: a,
		ctx:        ctx,
		poolId:     poolId,
	}
}

// Execute executes the request
func (a *StoragePoolAPIService) SetErasureCodingPolicyExecute(r ApiSetErasureCodingPolicyRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StoragePoolAPIService.SetErasureCodingPolicy")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/instances/StoragePool/{poolId}/action/setErasureCodingPolicy"
	localVarPath = strings.Replace(localVarPath, "{"+"poolId"+"}", url.PathEscape(parameterValueToString(r.poolId, "poolId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.setErasureCodingPolicy == nil {
		return nil, reportError("setErasureCodingPolicy is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.setErasureCodingPolicy
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
