/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
)

// checks if the DeviceGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceGroup{}

// DeviceGroup struct for DeviceGroup
type DeviceGroup struct {
	// Device Group ID
	Id *string `json:"id,omitempty"`
	// Device Group name
	Name *string `json:"name,omitempty"`
	// Protection Domain ID
	ProtectionDomainId *string `json:"protectionDomainId,omitempty"`
	// Number of devices
	NumOfDevices *int32 `json:"numOfDevices,omitempty"`
	// Usable capacity in KB
	UsableCapacityInKb *int32 `json:"usableCapacityInKb,omitempty"`
	// Used capacity in KB
	UsedCapacityInKb *int32 `json:"usedCapacityInKb,omitempty"`
	// Device Group status
	Status *string `json:"status,omitempty"`
	Links []Link `json:"links,omitempty"`
}

// NewDeviceGroup instantiates a new DeviceGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceGroup() *DeviceGroup {
	this := DeviceGroup{}
	return &this
}

// NewDeviceGroupWithDefaults instantiates a new DeviceGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceGroupWithDefaults() *DeviceGroup {
	this := DeviceGroup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeviceGroup) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeviceGroup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeviceGroup) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeviceGroup) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeviceGroup) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeviceGroup) SetName(v string) {
	o.Name = &v
}

// GetProtectionDomainId returns the ProtectionDomainId field value if set, zero value otherwise.
func (o *DeviceGroup) GetProtectionDomainId() string {
	if o == nil || IsNil(o.ProtectionDomainId) {
		var ret string
		return ret
	}
	return *o.ProtectionDomainId
}

// GetProtectionDomainIdOk returns a tuple with the ProtectionDomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetProtectionDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProtectionDomainId) {
		return nil, false
	}
	return o.ProtectionDomainId, true
}

// HasProtectionDomainId returns a boolean if a field has been set.
func (o *DeviceGroup) HasProtectionDomainId() bool {
	if o != nil && !IsNil(o.ProtectionDomainId) {
		return true
	}

	return false
}

// SetProtectionDomainId gets a reference to the given string and assigns it to the ProtectionDomainId field.
func (o *DeviceGroup) SetProtectionDomainId(v string) {
	o.ProtectionDomainId = &v
}

// GetNumOfDevices returns the NumOfDevices field value if set, zero value otherwise.
func (o *DeviceGroup) GetNumOfDevices() int32 {
	if o == nil || IsNil(o.NumOfDevices) {
		var ret int32
		return ret
	}
	return *o.NumOfDevices
}

// GetNumOfDevicesOk returns a tuple with the NumOfDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetNumOfDevicesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumOfDevices) {
		return nil, false
	}
	return o.NumOfDevices, true
}

// HasNumOfDevices returns a boolean if a field has been set.
func (o *DeviceGroup) HasNumOfDevices() bool {
	if o != nil && !IsNil(o.NumOfDevices) {
		return true
	}

	return false
}

// SetNumOfDevices gets a reference to the given int32 and assigns it to the NumOfDevices field.
func (o *DeviceGroup) SetNumOfDevices(v int32) {
	o.NumOfDevices = &v
}

// GetUsableCapacityInKb returns the UsableCapacityInKb field value if set, zero value otherwise.
func (o *DeviceGroup) GetUsableCapacityInKb() int32 {
	if o == nil || IsNil(o.UsableCapacityInKb) {
		var ret int32
		return ret
	}
	return *o.UsableCapacityInKb
}

// GetUsableCapacityInKbOk returns a tuple with the UsableCapacityInKb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetUsableCapacityInKbOk() (*int32, bool) {
	if o == nil || IsNil(o.UsableCapacityInKb) {
		return nil, false
	}
	return o.UsableCapacityInKb, true
}

// HasUsableCapacityInKb returns a boolean if a field has been set.
func (o *DeviceGroup) HasUsableCapacityInKb() bool {
	if o != nil && !IsNil(o.UsableCapacityInKb) {
		return true
	}

	return false
}

// SetUsableCapacityInKb gets a reference to the given int32 and assigns it to the UsableCapacityInKb field.
func (o *DeviceGroup) SetUsableCapacityInKb(v int32) {
	o.UsableCapacityInKb = &v
}

// GetUsedCapacityInKb returns the UsedCapacityInKb field value if set, zero value otherwise.
func (o *DeviceGroup) GetUsedCapacityInKb() int32 {
	if o == nil || IsNil(o.UsedCapacityInKb) {
		var ret int32
		return ret
	}
	return *o.UsedCapacityInKb
}

// GetUsedCapacityInKbOk returns a tuple with the UsedCapacityInKb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetUsedCapacityInKbOk() (*int32, bool) {
	if o == nil || IsNil(o.UsedCapacityInKb) {
		return nil, false
	}
	return o.UsedCapacityInKb, true
}

// HasUsedCapacityInKb returns a boolean if a field has been set.
func (o *DeviceGroup) HasUsedCapacityInKb() bool {
	if o != nil && !IsNil(o.UsedCapacityInKb) {
		return true
	}

	return false
}

// SetUsedCapacityInKb gets a reference to the given int32 and assigns it to the UsedCapacityInKb field.
func (o *DeviceGroup) SetUsedCapacityInKb(v int32) {
	o.UsedCapacityInKb = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeviceGroup) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeviceGroup) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeviceGroup) SetStatus(v string) {
	o.Status = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *DeviceGroup) GetLinks() []Link {
	if o == nil || IsNil(o.Links) {
		var ret []Link
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroup) GetLinksOk() ([]Link, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *DeviceGroup) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []Link and assigns it to the Links field.
func (o *DeviceGroup) SetLinks(v []Link) {
	o.Links = v
}

func (o DeviceGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ProtectionDomainId) {
		toSerialize["protectionDomainId"] = o.ProtectionDomainId
	}
	if !IsNil(o.NumOfDevices) {
		toSerialize["numOfDevices"] = o.NumOfDevices
	}
	if !IsNil(o.UsableCapacityInKb) {
		toSerialize["usableCapacityInKb"] = o.UsableCapacityInKb
	}
	if !IsNil(o.UsedCapacityInKb) {
		toSerialize["usedCapacityInKb"] = o.UsedCapacityInKb
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableDeviceGroup struct {
	value *DeviceGroup
	isSet bool
}

func (v NullableDeviceGroup) Get() *DeviceGroup {
	return v.value
}

func (v *NullableDeviceGroup) Set(val *DeviceGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceGroup(val *DeviceGroup) *NullableDeviceGroup {
	return &NullableDeviceGroup{value: val, isSet: true}
}

func (v NullableDeviceGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


