/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StorageNodeParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageNodeParam{}

// StorageNodeParam struct for StorageNodeParam
type StorageNodeParam struct {
	// Storage Node name
	Name *string `json:"name,omitempty"`
	// Protection Domain ID
	ProtectionDomainId string `json:"protectionDomainId"`
	// List of IP addresses with roles
	IpList []SdsIPList `json:"ipList"`
	// Fault Set ID
	FaultSetId *string `json:"faultSetId,omitempty"`
	// Port number
	Port *string `json:"port,omitempty"`
}

type _StorageNodeParam StorageNodeParam

// NewStorageNodeParam instantiates a new StorageNodeParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageNodeParam(protectionDomainId string, ipList []SdsIPList) *StorageNodeParam {
	this := StorageNodeParam{}
	this.ProtectionDomainId = protectionDomainId
	this.IpList = ipList
	return &this
}

// NewStorageNodeParamWithDefaults instantiates a new StorageNodeParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageNodeParamWithDefaults() *StorageNodeParam {
	this := StorageNodeParam{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StorageNodeParam) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNodeParam) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StorageNodeParam) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StorageNodeParam) SetName(v string) {
	o.Name = &v
}

// GetProtectionDomainId returns the ProtectionDomainId field value
func (o *StorageNodeParam) GetProtectionDomainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtectionDomainId
}

// GetProtectionDomainIdOk returns a tuple with the ProtectionDomainId field value
// and a boolean to check if the value has been set.
func (o *StorageNodeParam) GetProtectionDomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtectionDomainId, true
}

// SetProtectionDomainId sets field value
func (o *StorageNodeParam) SetProtectionDomainId(v string) {
	o.ProtectionDomainId = v
}

// GetIpList returns the IpList field value
func (o *StorageNodeParam) GetIpList() []SdsIPList {
	if o == nil {
		var ret []SdsIPList
		return ret
	}

	return o.IpList
}

// GetIpListOk returns a tuple with the IpList field value
// and a boolean to check if the value has been set.
func (o *StorageNodeParam) GetIpListOk() ([]SdsIPList, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpList, true
}

// SetIpList sets field value
func (o *StorageNodeParam) SetIpList(v []SdsIPList) {
	o.IpList = v
}

// GetFaultSetId returns the FaultSetId field value if set, zero value otherwise.
func (o *StorageNodeParam) GetFaultSetId() string {
	if o == nil || IsNil(o.FaultSetId) {
		var ret string
		return ret
	}
	return *o.FaultSetId
}

// GetFaultSetIdOk returns a tuple with the FaultSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNodeParam) GetFaultSetIdOk() (*string, bool) {
	if o == nil || IsNil(o.FaultSetId) {
		return nil, false
	}
	return o.FaultSetId, true
}

// HasFaultSetId returns a boolean if a field has been set.
func (o *StorageNodeParam) HasFaultSetId() bool {
	if o != nil && !IsNil(o.FaultSetId) {
		return true
	}

	return false
}

// SetFaultSetId gets a reference to the given string and assigns it to the FaultSetId field.
func (o *StorageNodeParam) SetFaultSetId(v string) {
	o.FaultSetId = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *StorageNodeParam) GetPort() string {
	if o == nil || IsNil(o.Port) {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNodeParam) GetPortOk() (*string, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *StorageNodeParam) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *StorageNodeParam) SetPort(v string) {
	o.Port = &v
}

func (o StorageNodeParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageNodeParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["protectionDomainId"] = o.ProtectionDomainId
	toSerialize["ipList"] = o.IpList
	if !IsNil(o.FaultSetId) {
		toSerialize["faultSetId"] = o.FaultSetId
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	return toSerialize, nil
}

func (o *StorageNodeParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protectionDomainId",
		"ipList",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageNodeParam := _StorageNodeParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStorageNodeParam)

	if err != nil {
		return err
	}

	*o = StorageNodeParam(varStorageNodeParam)

	return err
}

type NullableStorageNodeParam struct {
	value *StorageNodeParam
	isSet bool
}

func (v NullableStorageNodeParam) Get() *StorageNodeParam {
	return v.value
}

func (v *NullableStorageNodeParam) Set(val *StorageNodeParam) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageNodeParam) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageNodeParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageNodeParam(val *StorageNodeParam) *NullableStorageNodeParam {
	return &NullableStorageNodeParam{value: val, isSet: true}
}

func (v NullableStorageNodeParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageNodeParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


