/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetErasureCodingPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetErasureCodingPolicy{}

// SetErasureCodingPolicy struct for SetErasureCodingPolicy
type SetErasureCodingPolicy struct {
	// Erasure Coding policy to set
	ErasureCodingPolicy string `json:"erasureCodingPolicy"`
}

type _SetErasureCodingPolicy SetErasureCodingPolicy

// NewSetErasureCodingPolicy instantiates a new SetErasureCodingPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetErasureCodingPolicy(erasureCodingPolicy string) *SetErasureCodingPolicy {
	this := SetErasureCodingPolicy{}
	this.ErasureCodingPolicy = erasureCodingPolicy
	return &this
}

// NewSetErasureCodingPolicyWithDefaults instantiates a new SetErasureCodingPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetErasureCodingPolicyWithDefaults() *SetErasureCodingPolicy {
	this := SetErasureCodingPolicy{}
	return &this
}

// GetErasureCodingPolicy returns the ErasureCodingPolicy field value
func (o *SetErasureCodingPolicy) GetErasureCodingPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErasureCodingPolicy
}

// GetErasureCodingPolicyOk returns a tuple with the ErasureCodingPolicy field value
// and a boolean to check if the value has been set.
func (o *SetErasureCodingPolicy) GetErasureCodingPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErasureCodingPolicy, true
}

// SetErasureCodingPolicy sets field value
func (o *SetErasureCodingPolicy) SetErasureCodingPolicy(v string) {
	o.ErasureCodingPolicy = v
}

func (o SetErasureCodingPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetErasureCodingPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["erasureCodingPolicy"] = o.ErasureCodingPolicy
	return toSerialize, nil
}

func (o *SetErasureCodingPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"erasureCodingPolicy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetErasureCodingPolicy := _SetErasureCodingPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetErasureCodingPolicy)

	if err != nil {
		return err
	}

	*o = SetErasureCodingPolicy(varSetErasureCodingPolicy)

	return err
}

type NullableSetErasureCodingPolicy struct {
	value *SetErasureCodingPolicy
	isSet bool
}

func (v NullableSetErasureCodingPolicy) Get() *SetErasureCodingPolicy {
	return v.value
}

func (v *NullableSetErasureCodingPolicy) Set(val *SetErasureCodingPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableSetErasureCodingPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableSetErasureCodingPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetErasureCodingPolicy(val *SetErasureCodingPolicy) *NullableSetErasureCodingPolicy {
	return &NullableSetErasureCodingPolicy{value: val, isSet: true}
}

func (v NullableSetErasureCodingPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetErasureCodingPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


