/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceParamGen2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceParamGen2{}

// DeviceParamGen2 struct for DeviceParamGen2
type DeviceParamGen2 struct {
	// Device name
	Name *string `json:"name,omitempty"`
	// Device current path name
	DeviceCurrentPathname string `json:"deviceCurrentPathname"`
	// Capacity limit in KB
	CapacityLimitInKb *int32 `json:"capacityLimitInKb,omitempty"`
	// Storage Pool ID
	StoragePoolId string `json:"storagePoolId"`
	// Storage Node ID (Gen2 - replaces sdsId)
	NodeId *string `json:"nodeId,omitempty"`
	// Device Group ID (Gen2 - replaces sdsId)
	DeviceGroupId *string `json:"deviceGroupId,omitempty"`
	// Test time in seconds
	TestTimeSecs *int32 `json:"testTimeSecs,omitempty"`
	// Test mode
	TestMode *string `json:"testMode,omitempty"`
	// Media type
	MediaType *string `json:"mediaType,omitempty"`
	// External acceleration type
	ExternalAccelerationType *string `json:"externalAccelerationType,omitempty"`
}

type _DeviceParamGen2 DeviceParamGen2

// NewDeviceParamGen2 instantiates a new DeviceParamGen2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceParamGen2(deviceCurrentPathname string, storagePoolId string) *DeviceParamGen2 {
	this := DeviceParamGen2{}
	this.DeviceCurrentPathname = deviceCurrentPathname
	this.StoragePoolId = storagePoolId
	return &this
}

// NewDeviceParamGen2WithDefaults instantiates a new DeviceParamGen2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceParamGen2WithDefaults() *DeviceParamGen2 {
	this := DeviceParamGen2{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeviceParamGen2) SetName(v string) {
	o.Name = &v
}

// GetDeviceCurrentPathname returns the DeviceCurrentPathname field value
func (o *DeviceParamGen2) GetDeviceCurrentPathname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceCurrentPathname
}

// GetDeviceCurrentPathnameOk returns a tuple with the DeviceCurrentPathname field value
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetDeviceCurrentPathnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceCurrentPathname, true
}

// SetDeviceCurrentPathname sets field value
func (o *DeviceParamGen2) SetDeviceCurrentPathname(v string) {
	o.DeviceCurrentPathname = v
}

// GetCapacityLimitInKb returns the CapacityLimitInKb field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetCapacityLimitInKb() int32 {
	if o == nil || IsNil(o.CapacityLimitInKb) {
		var ret int32
		return ret
	}
	return *o.CapacityLimitInKb
}

// GetCapacityLimitInKbOk returns a tuple with the CapacityLimitInKb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetCapacityLimitInKbOk() (*int32, bool) {
	if o == nil || IsNil(o.CapacityLimitInKb) {
		return nil, false
	}
	return o.CapacityLimitInKb, true
}

// HasCapacityLimitInKb returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasCapacityLimitInKb() bool {
	if o != nil && !IsNil(o.CapacityLimitInKb) {
		return true
	}

	return false
}

// SetCapacityLimitInKb gets a reference to the given int32 and assigns it to the CapacityLimitInKb field.
func (o *DeviceParamGen2) SetCapacityLimitInKb(v int32) {
	o.CapacityLimitInKb = &v
}

// GetStoragePoolId returns the StoragePoolId field value
func (o *DeviceParamGen2) GetStoragePoolId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StoragePoolId
}

// GetStoragePoolIdOk returns a tuple with the StoragePoolId field value
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetStoragePoolIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoragePoolId, true
}

// SetStoragePoolId sets field value
func (o *DeviceParamGen2) SetStoragePoolId(v string) {
	o.StoragePoolId = v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetNodeId() string {
	if o == nil || IsNil(o.NodeId) {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *DeviceParamGen2) SetNodeId(v string) {
	o.NodeId = &v
}

// GetDeviceGroupId returns the DeviceGroupId field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetDeviceGroupId() string {
	if o == nil || IsNil(o.DeviceGroupId) {
		var ret string
		return ret
	}
	return *o.DeviceGroupId
}

// GetDeviceGroupIdOk returns a tuple with the DeviceGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetDeviceGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceGroupId) {
		return nil, false
	}
	return o.DeviceGroupId, true
}

// HasDeviceGroupId returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasDeviceGroupId() bool {
	if o != nil && !IsNil(o.DeviceGroupId) {
		return true
	}

	return false
}

// SetDeviceGroupId gets a reference to the given string and assigns it to the DeviceGroupId field.
func (o *DeviceParamGen2) SetDeviceGroupId(v string) {
	o.DeviceGroupId = &v
}

// GetTestTimeSecs returns the TestTimeSecs field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetTestTimeSecs() int32 {
	if o == nil || IsNil(o.TestTimeSecs) {
		var ret int32
		return ret
	}
	return *o.TestTimeSecs
}

// GetTestTimeSecsOk returns a tuple with the TestTimeSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetTestTimeSecsOk() (*int32, bool) {
	if o == nil || IsNil(o.TestTimeSecs) {
		return nil, false
	}
	return o.TestTimeSecs, true
}

// HasTestTimeSecs returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasTestTimeSecs() bool {
	if o != nil && !IsNil(o.TestTimeSecs) {
		return true
	}

	return false
}

// SetTestTimeSecs gets a reference to the given int32 and assigns it to the TestTimeSecs field.
func (o *DeviceParamGen2) SetTestTimeSecs(v int32) {
	o.TestTimeSecs = &v
}

// GetTestMode returns the TestMode field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetTestMode() string {
	if o == nil || IsNil(o.TestMode) {
		var ret string
		return ret
	}
	return *o.TestMode
}

// GetTestModeOk returns a tuple with the TestMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetTestModeOk() (*string, bool) {
	if o == nil || IsNil(o.TestMode) {
		return nil, false
	}
	return o.TestMode, true
}

// HasTestMode returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasTestMode() bool {
	if o != nil && !IsNil(o.TestMode) {
		return true
	}

	return false
}

// SetTestMode gets a reference to the given string and assigns it to the TestMode field.
func (o *DeviceParamGen2) SetTestMode(v string) {
	o.TestMode = &v
}

// GetMediaType returns the MediaType field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetMediaType() string {
	if o == nil || IsNil(o.MediaType) {
		var ret string
		return ret
	}
	return *o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetMediaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MediaType) {
		return nil, false
	}
	return o.MediaType, true
}

// HasMediaType returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasMediaType() bool {
	if o != nil && !IsNil(o.MediaType) {
		return true
	}

	return false
}

// SetMediaType gets a reference to the given string and assigns it to the MediaType field.
func (o *DeviceParamGen2) SetMediaType(v string) {
	o.MediaType = &v
}

// GetExternalAccelerationType returns the ExternalAccelerationType field value if set, zero value otherwise.
func (o *DeviceParamGen2) GetExternalAccelerationType() string {
	if o == nil || IsNil(o.ExternalAccelerationType) {
		var ret string
		return ret
	}
	return *o.ExternalAccelerationType
}

// GetExternalAccelerationTypeOk returns a tuple with the ExternalAccelerationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceParamGen2) GetExternalAccelerationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalAccelerationType) {
		return nil, false
	}
	return o.ExternalAccelerationType, true
}

// HasExternalAccelerationType returns a boolean if a field has been set.
func (o *DeviceParamGen2) HasExternalAccelerationType() bool {
	if o != nil && !IsNil(o.ExternalAccelerationType) {
		return true
	}

	return false
}

// SetExternalAccelerationType gets a reference to the given string and assigns it to the ExternalAccelerationType field.
func (o *DeviceParamGen2) SetExternalAccelerationType(v string) {
	o.ExternalAccelerationType = &v
}

func (o DeviceParamGen2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceParamGen2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["deviceCurrentPathname"] = o.DeviceCurrentPathname
	if !IsNil(o.CapacityLimitInKb) {
		toSerialize["capacityLimitInKb"] = o.CapacityLimitInKb
	}
	toSerialize["storagePoolId"] = o.StoragePoolId
	if !IsNil(o.NodeId) {
		toSerialize["nodeId"] = o.NodeId
	}
	if !IsNil(o.DeviceGroupId) {
		toSerialize["deviceGroupId"] = o.DeviceGroupId
	}
	if !IsNil(o.TestTimeSecs) {
		toSerialize["testTimeSecs"] = o.TestTimeSecs
	}
	if !IsNil(o.TestMode) {
		toSerialize["testMode"] = o.TestMode
	}
	if !IsNil(o.MediaType) {
		toSerialize["mediaType"] = o.MediaType
	}
	if !IsNil(o.ExternalAccelerationType) {
		toSerialize["externalAccelerationType"] = o.ExternalAccelerationType
	}
	return toSerialize, nil
}

func (o *DeviceParamGen2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deviceCurrentPathname",
		"storagePoolId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceParamGen2 := _DeviceParamGen2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceParamGen2)

	if err != nil {
		return err
	}

	*o = DeviceParamGen2(varDeviceParamGen2)

	return err
}

type NullableDeviceParamGen2 struct {
	value *DeviceParamGen2
	isSet bool
}

func (v NullableDeviceParamGen2) Get() *DeviceParamGen2 {
	return v.value
}

func (v *NullableDeviceParamGen2) Set(val *DeviceParamGen2) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceParamGen2) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceParamGen2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceParamGen2(val *DeviceParamGen2) *NullableDeviceParamGen2 {
	return &NullableDeviceParamGen2{value: val, isSet: true}
}

func (v NullableDeviceParamGen2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceParamGen2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


