/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
)

// checks if the StorageNodeResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageNodeResp{}

// StorageNodeResp struct for StorageNodeResp
type StorageNodeResp struct {
	// Created Storage Node ID
	Id *string `json:"id,omitempty"`
}

// NewStorageNodeResp instantiates a new StorageNodeResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageNodeResp() *StorageNodeResp {
	this := StorageNodeResp{}
	return &this
}

// NewStorageNodeRespWithDefaults instantiates a new StorageNodeResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageNodeRespWithDefaults() *StorageNodeResp {
	this := StorageNodeResp{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StorageNodeResp) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNodeResp) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StorageNodeResp) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StorageNodeResp) SetId(v string) {
	o.Id = &v
}

func (o StorageNodeResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageNodeResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableStorageNodeResp struct {
	value *StorageNodeResp
	isSet bool
}

func (v NullableStorageNodeResp) Get() *StorageNodeResp {
	return v.value
}

func (v *NullableStorageNodeResp) Set(val *StorageNodeResp) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageNodeResp) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageNodeResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageNodeResp(val *StorageNodeResp) *NullableStorageNodeResp {
	return &NullableStorageNodeResp{value: val, isSet: true}
}

func (v NullableStorageNodeResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageNodeResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


