/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
)

// checks if the SdsIPList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdsIPList{}

// SdsIPList struct for SdsIPList
type SdsIPList struct {
	SdsIp *SdsIP `json:"sdsIp,omitempty"`
}

// NewSdsIPList instantiates a new SdsIPList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdsIPList() *SdsIPList {
	this := SdsIPList{}
	return &this
}

// NewSdsIPListWithDefaults instantiates a new SdsIPList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdsIPListWithDefaults() *SdsIPList {
	this := SdsIPList{}
	return &this
}

// GetSdsIp returns the SdsIp field value if set, zero value otherwise.
func (o *SdsIPList) GetSdsIp() SdsIP {
	if o == nil || IsNil(o.SdsIp) {
		var ret SdsIP
		return ret
	}
	return *o.SdsIp
}

// GetSdsIpOk returns a tuple with the SdsIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdsIPList) GetSdsIpOk() (*SdsIP, bool) {
	if o == nil || IsNil(o.SdsIp) {
		return nil, false
	}
	return o.SdsIp, true
}

// HasSdsIp returns a boolean if a field has been set.
func (o *SdsIPList) HasSdsIp() bool {
	if o != nil && !IsNil(o.SdsIp) {
		return true
	}

	return false
}

// SetSdsIp gets a reference to the given SdsIP and assigns it to the SdsIp field.
func (o *SdsIPList) SetSdsIp(v SdsIP) {
	o.SdsIp = &v
}

func (o SdsIPList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdsIPList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SdsIp) {
		toSerialize["sdsIp"] = o.SdsIp
	}
	return toSerialize, nil
}

type NullableSdsIPList struct {
	value *SdsIPList
	isSet bool
}

func (v NullableSdsIPList) Get() *SdsIPList {
	return v.value
}

func (v *NullableSdsIPList) Set(val *SdsIPList) {
	v.value = val
	v.isSet = true
}

func (v NullableSdsIPList) IsSet() bool {
	return v.isSet
}

func (v *NullableSdsIPList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdsIPList(val *SdsIPList) *NullableSdsIPList {
	return &NullableSdsIPList{value: val, isSet: true}
}

func (v NullableSdsIPList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdsIPList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


