/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
)

// checks if the DeviceGroupResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceGroupResp{}

// DeviceGroupResp struct for DeviceGroupResp
type DeviceGroupResp struct {
	// Created Device Group ID
	Id *string `json:"id,omitempty"`
}

// NewDeviceGroupResp instantiates a new DeviceGroupResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceGroupResp() *DeviceGroupResp {
	this := DeviceGroupResp{}
	return &this
}

// NewDeviceGroupRespWithDefaults instantiates a new DeviceGroupResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceGroupRespWithDefaults() *DeviceGroupResp {
	this := DeviceGroupResp{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeviceGroupResp) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroupResp) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeviceGroupResp) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeviceGroupResp) SetId(v string) {
	o.Id = &v
}

func (o DeviceGroupResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceGroupResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableDeviceGroupResp struct {
	value *DeviceGroupResp
	isSet bool
}

func (v NullableDeviceGroupResp) Get() *DeviceGroupResp {
	return v.value
}

func (v *NullableDeviceGroupResp) Set(val *DeviceGroupResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceGroupResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceGroupResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceGroupResp(val *DeviceGroupResp) *NullableDeviceGroupResp {
	return &NullableDeviceGroupResp{value: val, isSet: true}
}

func (v NullableDeviceGroupResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceGroupResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


