/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetStorageNodeName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetStorageNodeName{}

// SetStorageNodeName struct for SetStorageNodeName
type SetStorageNodeName struct {
	// New Storage Node name
	Name string `json:"name"`
}

type _SetStorageNodeName SetStorageNodeName

// NewSetStorageNodeName instantiates a new SetStorageNodeName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetStorageNodeName(name string) *SetStorageNodeName {
	this := SetStorageNodeName{}
	this.Name = name
	return &this
}

// NewSetStorageNodeNameWithDefaults instantiates a new SetStorageNodeName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetStorageNodeNameWithDefaults() *SetStorageNodeName {
	this := SetStorageNodeName{}
	return &this
}

// GetName returns the Name field value
func (o *SetStorageNodeName) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SetStorageNodeName) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SetStorageNodeName) SetName(v string) {
	o.Name = v
}

func (o SetStorageNodeName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetStorageNodeName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SetStorageNodeName) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetStorageNodeName := _SetStorageNodeName{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetStorageNodeName)

	if err != nil {
		return err
	}

	*o = SetStorageNodeName(varSetStorageNodeName)

	return err
}

type NullableSetStorageNodeName struct {
	value *SetStorageNodeName
	isSet bool
}

func (v NullableSetStorageNodeName) Get() *SetStorageNodeName {
	return v.value
}

func (v *NullableSetStorageNodeName) Set(val *SetStorageNodeName) {
	v.value = val
	v.isSet = true
}

func (v NullableSetStorageNodeName) IsSet() bool {
	return v.isSet
}

func (v *NullableSetStorageNodeName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetStorageNodeName(val *SetStorageNodeName) *NullableSetStorageNodeName {
	return &NullableSetStorageNodeName{value: val, isSet: true}
}

func (v NullableSetStorageNodeName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetStorageNodeName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


