/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetDeviceGroupName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDeviceGroupName{}

// SetDeviceGroupName struct for SetDeviceGroupName
type SetDeviceGroupName struct {
	// New Device Group name
	Name string `json:"name"`
}

type _SetDeviceGroupName SetDeviceGroupName

// NewSetDeviceGroupName instantiates a new SetDeviceGroupName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDeviceGroupName(name string) *SetDeviceGroupName {
	this := SetDeviceGroupName{}
	this.Name = name
	return &this
}

// NewSetDeviceGroupNameWithDefaults instantiates a new SetDeviceGroupName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDeviceGroupNameWithDefaults() *SetDeviceGroupName {
	this := SetDeviceGroupName{}
	return &this
}

// GetName returns the Name field value
func (o *SetDeviceGroupName) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SetDeviceGroupName) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SetDeviceGroupName) SetName(v string) {
	o.Name = v
}

func (o SetDeviceGroupName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDeviceGroupName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SetDeviceGroupName) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDeviceGroupName := _SetDeviceGroupName{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetDeviceGroupName)

	if err != nil {
		return err
	}

	*o = SetDeviceGroupName(varSetDeviceGroupName)

	return err
}

type NullableSetDeviceGroupName struct {
	value *SetDeviceGroupName
	isSet bool
}

func (v NullableSetDeviceGroupName) Get() *SetDeviceGroupName {
	return v.value
}

func (v *NullableSetDeviceGroupName) Set(val *SetDeviceGroupName) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDeviceGroupName) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDeviceGroupName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDeviceGroupName(val *SetDeviceGroupName) *NullableSetDeviceGroupName {
	return &NullableSetDeviceGroupName{value: val, isSet: true}
}

func (v NullableSetDeviceGroupName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDeviceGroupName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


