/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
)

// checks if the SdsIP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdsIP{}

// SdsIP struct for SdsIP
type SdsIP struct {
	// IP address
	Ip *string `json:"ip,omitempty"`
	// IP role (e.g., SdsOnly, SdcOnly, All)
	Role *string `json:"role,omitempty"`
}

// NewSdsIP instantiates a new SdsIP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdsIP() *SdsIP {
	this := SdsIP{}
	return &this
}

// NewSdsIPWithDefaults instantiates a new SdsIP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdsIPWithDefaults() *SdsIP {
	this := SdsIP{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *SdsIP) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdsIP) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *SdsIP) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *SdsIP) SetIp(v string) {
	o.Ip = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *SdsIP) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdsIP) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *SdsIP) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *SdsIP) SetRole(v string) {
	o.Role = &v
}

func (o SdsIP) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdsIP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableSdsIP struct {
	value *SdsIP
	isSet bool
}

func (v NullableSdsIP) Get() *SdsIP {
	return v.value
}

func (v *NullableSdsIP) Set(val *SdsIP) {
	v.value = val
	v.isSet = true
}

func (v NullableSdsIP) IsSet() bool {
	return v.isSet
}

func (v *NullableSdsIP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdsIP(val *SdsIP) *NullableSdsIP {
	return &NullableSdsIP{value: val, isSet: true}
}

func (v NullableSdsIP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdsIP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


