/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
)

// checks if the StorageNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageNode{}

// StorageNode struct for StorageNode
type StorageNode struct {
	// Storage Node ID
	Id *string `json:"id,omitempty"`
	// Storage Node name
	Name *string `json:"name,omitempty"`
	// Protection Domain ID
	ProtectionDomainId *string `json:"protectionDomainId,omitempty"`
	// List of IP addresses
	IpAddresses []string `json:"ipAddresses,omitempty"`
	// Storage Node type
	StorageNodeType *string `json:"storageNodeType,omitempty"`
	// Fault Set ID
	FaultSetId *string `json:"faultSetId,omitempty"`
	// Storage Node status
	Status *string `json:"status,omitempty"`
	// Storage Node state
	State *string `json:"state,omitempty"`
	// Membership state
	MembershipState *string `json:"membershipState,omitempty"`
	// MDM connection state
	MdmConnectionState *string `json:"mdmConnectionState,omitempty"`
	// Software version
	SoftwareVersion *string `json:"softwareVersion,omitempty"`
	// Port number
	Port *int32 `json:"port,omitempty"`
	// Number of devices
	NumOfDevices *int32 `json:"numOfDevices,omitempty"`
	// Total capacity in KB
	TotalCapacityInKb *int32 `json:"totalCapacityInKb,omitempty"`
	// Used capacity in KB
	UsedCapacityInKb *int32 `json:"usedCapacityInKb,omitempty"`
	// Maintenance state
	MaintenanceState *string `json:"maintenanceState,omitempty"`
	// Performance profile
	PerformanceProfile *string `json:"performanceProfile,omitempty"`
	Links []Link `json:"links,omitempty"`
}

// NewStorageNode instantiates a new StorageNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageNode() *StorageNode {
	this := StorageNode{}
	return &this
}

// NewStorageNodeWithDefaults instantiates a new StorageNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageNodeWithDefaults() *StorageNode {
	this := StorageNode{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StorageNode) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StorageNode) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StorageNode) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StorageNode) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StorageNode) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StorageNode) SetName(v string) {
	o.Name = &v
}

// GetProtectionDomainId returns the ProtectionDomainId field value if set, zero value otherwise.
func (o *StorageNode) GetProtectionDomainId() string {
	if o == nil || IsNil(o.ProtectionDomainId) {
		var ret string
		return ret
	}
	return *o.ProtectionDomainId
}

// GetProtectionDomainIdOk returns a tuple with the ProtectionDomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetProtectionDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProtectionDomainId) {
		return nil, false
	}
	return o.ProtectionDomainId, true
}

// HasProtectionDomainId returns a boolean if a field has been set.
func (o *StorageNode) HasProtectionDomainId() bool {
	if o != nil && !IsNil(o.ProtectionDomainId) {
		return true
	}

	return false
}

// SetProtectionDomainId gets a reference to the given string and assigns it to the ProtectionDomainId field.
func (o *StorageNode) SetProtectionDomainId(v string) {
	o.ProtectionDomainId = &v
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *StorageNode) GetIpAddresses() []string {
	if o == nil || IsNil(o.IpAddresses) {
		var ret []string
		return ret
	}
	return o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetIpAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.IpAddresses) {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *StorageNode) HasIpAddresses() bool {
	if o != nil && !IsNil(o.IpAddresses) {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []string and assigns it to the IpAddresses field.
func (o *StorageNode) SetIpAddresses(v []string) {
	o.IpAddresses = v
}

// GetStorageNodeType returns the StorageNodeType field value if set, zero value otherwise.
func (o *StorageNode) GetStorageNodeType() string {
	if o == nil || IsNil(o.StorageNodeType) {
		var ret string
		return ret
	}
	return *o.StorageNodeType
}

// GetStorageNodeTypeOk returns a tuple with the StorageNodeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetStorageNodeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.StorageNodeType) {
		return nil, false
	}
	return o.StorageNodeType, true
}

// HasStorageNodeType returns a boolean if a field has been set.
func (o *StorageNode) HasStorageNodeType() bool {
	if o != nil && !IsNil(o.StorageNodeType) {
		return true
	}

	return false
}

// SetStorageNodeType gets a reference to the given string and assigns it to the StorageNodeType field.
func (o *StorageNode) SetStorageNodeType(v string) {
	o.StorageNodeType = &v
}

// GetFaultSetId returns the FaultSetId field value if set, zero value otherwise.
func (o *StorageNode) GetFaultSetId() string {
	if o == nil || IsNil(o.FaultSetId) {
		var ret string
		return ret
	}
	return *o.FaultSetId
}

// GetFaultSetIdOk returns a tuple with the FaultSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetFaultSetIdOk() (*string, bool) {
	if o == nil || IsNil(o.FaultSetId) {
		return nil, false
	}
	return o.FaultSetId, true
}

// HasFaultSetId returns a boolean if a field has been set.
func (o *StorageNode) HasFaultSetId() bool {
	if o != nil && !IsNil(o.FaultSetId) {
		return true
	}

	return false
}

// SetFaultSetId gets a reference to the given string and assigns it to the FaultSetId field.
func (o *StorageNode) SetFaultSetId(v string) {
	o.FaultSetId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StorageNode) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StorageNode) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *StorageNode) SetStatus(v string) {
	o.Status = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *StorageNode) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *StorageNode) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *StorageNode) SetState(v string) {
	o.State = &v
}

// GetMembershipState returns the MembershipState field value if set, zero value otherwise.
func (o *StorageNode) GetMembershipState() string {
	if o == nil || IsNil(o.MembershipState) {
		var ret string
		return ret
	}
	return *o.MembershipState
}

// GetMembershipStateOk returns a tuple with the MembershipState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetMembershipStateOk() (*string, bool) {
	if o == nil || IsNil(o.MembershipState) {
		return nil, false
	}
	return o.MembershipState, true
}

// HasMembershipState returns a boolean if a field has been set.
func (o *StorageNode) HasMembershipState() bool {
	if o != nil && !IsNil(o.MembershipState) {
		return true
	}

	return false
}

// SetMembershipState gets a reference to the given string and assigns it to the MembershipState field.
func (o *StorageNode) SetMembershipState(v string) {
	o.MembershipState = &v
}

// GetMdmConnectionState returns the MdmConnectionState field value if set, zero value otherwise.
func (o *StorageNode) GetMdmConnectionState() string {
	if o == nil || IsNil(o.MdmConnectionState) {
		var ret string
		return ret
	}
	return *o.MdmConnectionState
}

// GetMdmConnectionStateOk returns a tuple with the MdmConnectionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetMdmConnectionStateOk() (*string, bool) {
	if o == nil || IsNil(o.MdmConnectionState) {
		return nil, false
	}
	return o.MdmConnectionState, true
}

// HasMdmConnectionState returns a boolean if a field has been set.
func (o *StorageNode) HasMdmConnectionState() bool {
	if o != nil && !IsNil(o.MdmConnectionState) {
		return true
	}

	return false
}

// SetMdmConnectionState gets a reference to the given string and assigns it to the MdmConnectionState field.
func (o *StorageNode) SetMdmConnectionState(v string) {
	o.MdmConnectionState = &v
}

// GetSoftwareVersion returns the SoftwareVersion field value if set, zero value otherwise.
func (o *StorageNode) GetSoftwareVersion() string {
	if o == nil || IsNil(o.SoftwareVersion) {
		var ret string
		return ret
	}
	return *o.SoftwareVersion
}

// GetSoftwareVersionOk returns a tuple with the SoftwareVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetSoftwareVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SoftwareVersion) {
		return nil, false
	}
	return o.SoftwareVersion, true
}

// HasSoftwareVersion returns a boolean if a field has been set.
func (o *StorageNode) HasSoftwareVersion() bool {
	if o != nil && !IsNil(o.SoftwareVersion) {
		return true
	}

	return false
}

// SetSoftwareVersion gets a reference to the given string and assigns it to the SoftwareVersion field.
func (o *StorageNode) SetSoftwareVersion(v string) {
	o.SoftwareVersion = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *StorageNode) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *StorageNode) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *StorageNode) SetPort(v int32) {
	o.Port = &v
}

// GetNumOfDevices returns the NumOfDevices field value if set, zero value otherwise.
func (o *StorageNode) GetNumOfDevices() int32 {
	if o == nil || IsNil(o.NumOfDevices) {
		var ret int32
		return ret
	}
	return *o.NumOfDevices
}

// GetNumOfDevicesOk returns a tuple with the NumOfDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetNumOfDevicesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumOfDevices) {
		return nil, false
	}
	return o.NumOfDevices, true
}

// HasNumOfDevices returns a boolean if a field has been set.
func (o *StorageNode) HasNumOfDevices() bool {
	if o != nil && !IsNil(o.NumOfDevices) {
		return true
	}

	return false
}

// SetNumOfDevices gets a reference to the given int32 and assigns it to the NumOfDevices field.
func (o *StorageNode) SetNumOfDevices(v int32) {
	o.NumOfDevices = &v
}

// GetTotalCapacityInKb returns the TotalCapacityInKb field value if set, zero value otherwise.
func (o *StorageNode) GetTotalCapacityInKb() int32 {
	if o == nil || IsNil(o.TotalCapacityInKb) {
		var ret int32
		return ret
	}
	return *o.TotalCapacityInKb
}

// GetTotalCapacityInKbOk returns a tuple with the TotalCapacityInKb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetTotalCapacityInKbOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCapacityInKb) {
		return nil, false
	}
	return o.TotalCapacityInKb, true
}

// HasTotalCapacityInKb returns a boolean if a field has been set.
func (o *StorageNode) HasTotalCapacityInKb() bool {
	if o != nil && !IsNil(o.TotalCapacityInKb) {
		return true
	}

	return false
}

// SetTotalCapacityInKb gets a reference to the given int32 and assigns it to the TotalCapacityInKb field.
func (o *StorageNode) SetTotalCapacityInKb(v int32) {
	o.TotalCapacityInKb = &v
}

// GetUsedCapacityInKb returns the UsedCapacityInKb field value if set, zero value otherwise.
func (o *StorageNode) GetUsedCapacityInKb() int32 {
	if o == nil || IsNil(o.UsedCapacityInKb) {
		var ret int32
		return ret
	}
	return *o.UsedCapacityInKb
}

// GetUsedCapacityInKbOk returns a tuple with the UsedCapacityInKb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetUsedCapacityInKbOk() (*int32, bool) {
	if o == nil || IsNil(o.UsedCapacityInKb) {
		return nil, false
	}
	return o.UsedCapacityInKb, true
}

// HasUsedCapacityInKb returns a boolean if a field has been set.
func (o *StorageNode) HasUsedCapacityInKb() bool {
	if o != nil && !IsNil(o.UsedCapacityInKb) {
		return true
	}

	return false
}

// SetUsedCapacityInKb gets a reference to the given int32 and assigns it to the UsedCapacityInKb field.
func (o *StorageNode) SetUsedCapacityInKb(v int32) {
	o.UsedCapacityInKb = &v
}

// GetMaintenanceState returns the MaintenanceState field value if set, zero value otherwise.
func (o *StorageNode) GetMaintenanceState() string {
	if o == nil || IsNil(o.MaintenanceState) {
		var ret string
		return ret
	}
	return *o.MaintenanceState
}

// GetMaintenanceStateOk returns a tuple with the MaintenanceState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetMaintenanceStateOk() (*string, bool) {
	if o == nil || IsNil(o.MaintenanceState) {
		return nil, false
	}
	return o.MaintenanceState, true
}

// HasMaintenanceState returns a boolean if a field has been set.
func (o *StorageNode) HasMaintenanceState() bool {
	if o != nil && !IsNil(o.MaintenanceState) {
		return true
	}

	return false
}

// SetMaintenanceState gets a reference to the given string and assigns it to the MaintenanceState field.
func (o *StorageNode) SetMaintenanceState(v string) {
	o.MaintenanceState = &v
}

// GetPerformanceProfile returns the PerformanceProfile field value if set, zero value otherwise.
func (o *StorageNode) GetPerformanceProfile() string {
	if o == nil || IsNil(o.PerformanceProfile) {
		var ret string
		return ret
	}
	return *o.PerformanceProfile
}

// GetPerformanceProfileOk returns a tuple with the PerformanceProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetPerformanceProfileOk() (*string, bool) {
	if o == nil || IsNil(o.PerformanceProfile) {
		return nil, false
	}
	return o.PerformanceProfile, true
}

// HasPerformanceProfile returns a boolean if a field has been set.
func (o *StorageNode) HasPerformanceProfile() bool {
	if o != nil && !IsNil(o.PerformanceProfile) {
		return true
	}

	return false
}

// SetPerformanceProfile gets a reference to the given string and assigns it to the PerformanceProfile field.
func (o *StorageNode) SetPerformanceProfile(v string) {
	o.PerformanceProfile = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *StorageNode) GetLinks() []Link {
	if o == nil || IsNil(o.Links) {
		var ret []Link
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageNode) GetLinksOk() ([]Link, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *StorageNode) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []Link and assigns it to the Links field.
func (o *StorageNode) SetLinks(v []Link) {
	o.Links = v
}

func (o StorageNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ProtectionDomainId) {
		toSerialize["protectionDomainId"] = o.ProtectionDomainId
	}
	if !IsNil(o.IpAddresses) {
		toSerialize["ipAddresses"] = o.IpAddresses
	}
	if !IsNil(o.StorageNodeType) {
		toSerialize["storageNodeType"] = o.StorageNodeType
	}
	if !IsNil(o.FaultSetId) {
		toSerialize["faultSetId"] = o.FaultSetId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.MembershipState) {
		toSerialize["membershipState"] = o.MembershipState
	}
	if !IsNil(o.MdmConnectionState) {
		toSerialize["mdmConnectionState"] = o.MdmConnectionState
	}
	if !IsNil(o.SoftwareVersion) {
		toSerialize["softwareVersion"] = o.SoftwareVersion
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.NumOfDevices) {
		toSerialize["numOfDevices"] = o.NumOfDevices
	}
	if !IsNil(o.TotalCapacityInKb) {
		toSerialize["totalCapacityInKb"] = o.TotalCapacityInKb
	}
	if !IsNil(o.UsedCapacityInKb) {
		toSerialize["usedCapacityInKb"] = o.UsedCapacityInKb
	}
	if !IsNil(o.MaintenanceState) {
		toSerialize["maintenanceState"] = o.MaintenanceState
	}
	if !IsNil(o.PerformanceProfile) {
		toSerialize["performanceProfile"] = o.PerformanceProfile
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableStorageNode struct {
	value *StorageNode
	isSet bool
}

func (v NullableStorageNode) Get() *StorageNode {
	return v.value
}

func (v *NullableStorageNode) Set(val *StorageNode) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageNode) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageNode(val *StorageNode) *NullableStorageNode {
	return &NullableStorageNode{value: val, isSet: true}
}

func (v NullableStorageNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


