/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceGroupParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceGroupParam{}

// DeviceGroupParam struct for DeviceGroupParam
type DeviceGroupParam struct {
	// Device Group name
	Name *string `json:"name,omitempty"`
	// Protection Domain ID
	ProtectionDomainId string `json:"protectionDomainId"`
}

type _DeviceGroupParam DeviceGroupParam

// NewDeviceGroupParam instantiates a new DeviceGroupParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceGroupParam(protectionDomainId string) *DeviceGroupParam {
	this := DeviceGroupParam{}
	this.ProtectionDomainId = protectionDomainId
	return &this
}

// NewDeviceGroupParamWithDefaults instantiates a new DeviceGroupParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceGroupParamWithDefaults() *DeviceGroupParam {
	this := DeviceGroupParam{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeviceGroupParam) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceGroupParam) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeviceGroupParam) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeviceGroupParam) SetName(v string) {
	o.Name = &v
}

// GetProtectionDomainId returns the ProtectionDomainId field value
func (o *DeviceGroupParam) GetProtectionDomainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtectionDomainId
}

// GetProtectionDomainIdOk returns a tuple with the ProtectionDomainId field value
// and a boolean to check if the value has been set.
func (o *DeviceGroupParam) GetProtectionDomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtectionDomainId, true
}

// SetProtectionDomainId sets field value
func (o *DeviceGroupParam) SetProtectionDomainId(v string) {
	o.ProtectionDomainId = v
}

func (o DeviceGroupParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceGroupParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["protectionDomainId"] = o.ProtectionDomainId
	return toSerialize, nil
}

func (o *DeviceGroupParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protectionDomainId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceGroupParam := _DeviceGroupParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceGroupParam)

	if err != nil {
		return err
	}

	*o = DeviceGroupParam(varDeviceGroupParam)

	return err
}

type NullableDeviceGroupParam struct {
	value *DeviceGroupParam
	isSet bool
}

func (v NullableDeviceGroupParam) Get() *DeviceGroupParam {
	return v.value
}

func (v *NullableDeviceGroupParam) Set(val *DeviceGroupParam) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceGroupParam) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceGroupParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceGroupParam(val *DeviceGroupParam) *NullableDeviceGroupParam {
	return &NullableDeviceGroupParam{value: val, isSet: true}
}

func (v NullableDeviceGroupParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceGroupParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


