/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StoragePoolParamGen2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoragePoolParamGen2{}

// StoragePoolParamGen2 struct for StoragePoolParamGen2
type StoragePoolParamGen2 struct {
	// Storage Pool name
	Name string `json:"name"`
	// Protection Domain ID
	ProtectionDomainId string `json:"protectionDomainId"`
	// Media type
	MediaType *string `json:"mediaType,omitempty"`
	// Spare percentage
	SparePercentage *string `json:"sparePercentage,omitempty"`
	// Rebuild enabled
	RebuildEnabled *bool `json:"rebuildEnabled,omitempty"`
	// Rebalance enabled
	RebalanceEnabled *bool `json:"rebalanceEnabled,omitempty"`
	// Zero padding enabled
	ZeroPaddingEnabled *string `json:"zeroPaddingEnabled,omitempty"`
	// Use Read Memory Cache
	UseRmcache *string `json:"useRmcache,omitempty"`
	// Use Read Flash Cache
	UseRfcache *string `json:"useRfcache,omitempty"`
	// RMCache write handling mode
	RmcacheWriteHandlingMode *string `json:"rmcacheWriteHandlingMode,omitempty"`
	// Erasure Coding policy (e.g., RS_4_2, RS_6_2, RS_8_2, RS_10_2)
	ErasureCodingPolicy *string `json:"erasureCodingPolicy,omitempty"`
	// Number of data blocks for EC
	NumDataBlocks *int32 `json:"numDataBlocks,omitempty"`
	// Number of parity blocks for EC
	NumParityBlocks *int32 `json:"numParityBlocks,omitempty"`
	// Protection scheme
	ProtectionScheme *string `json:"protectionScheme,omitempty"`
	// Compression method
	CompressionMethod *string `json:"compressionMethod,omitempty"`
}

type _StoragePoolParamGen2 StoragePoolParamGen2

// NewStoragePoolParamGen2 instantiates a new StoragePoolParamGen2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoragePoolParamGen2(name string, protectionDomainId string) *StoragePoolParamGen2 {
	this := StoragePoolParamGen2{}
	this.Name = name
	this.ProtectionDomainId = protectionDomainId
	return &this
}

// NewStoragePoolParamGen2WithDefaults instantiates a new StoragePoolParamGen2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoragePoolParamGen2WithDefaults() *StoragePoolParamGen2 {
	this := StoragePoolParamGen2{}
	return &this
}

// GetName returns the Name field value
func (o *StoragePoolParamGen2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StoragePoolParamGen2) SetName(v string) {
	o.Name = v
}

// GetProtectionDomainId returns the ProtectionDomainId field value
func (o *StoragePoolParamGen2) GetProtectionDomainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtectionDomainId
}

// GetProtectionDomainIdOk returns a tuple with the ProtectionDomainId field value
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetProtectionDomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtectionDomainId, true
}

// SetProtectionDomainId sets field value
func (o *StoragePoolParamGen2) SetProtectionDomainId(v string) {
	o.ProtectionDomainId = v
}

// GetMediaType returns the MediaType field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetMediaType() string {
	if o == nil || IsNil(o.MediaType) {
		var ret string
		return ret
	}
	return *o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetMediaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MediaType) {
		return nil, false
	}
	return o.MediaType, true
}

// HasMediaType returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasMediaType() bool {
	if o != nil && !IsNil(o.MediaType) {
		return true
	}

	return false
}

// SetMediaType gets a reference to the given string and assigns it to the MediaType field.
func (o *StoragePoolParamGen2) SetMediaType(v string) {
	o.MediaType = &v
}

// GetSparePercentage returns the SparePercentage field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetSparePercentage() string {
	if o == nil || IsNil(o.SparePercentage) {
		var ret string
		return ret
	}
	return *o.SparePercentage
}

// GetSparePercentageOk returns a tuple with the SparePercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetSparePercentageOk() (*string, bool) {
	if o == nil || IsNil(o.SparePercentage) {
		return nil, false
	}
	return o.SparePercentage, true
}

// HasSparePercentage returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasSparePercentage() bool {
	if o != nil && !IsNil(o.SparePercentage) {
		return true
	}

	return false
}

// SetSparePercentage gets a reference to the given string and assigns it to the SparePercentage field.
func (o *StoragePoolParamGen2) SetSparePercentage(v string) {
	o.SparePercentage = &v
}

// GetRebuildEnabled returns the RebuildEnabled field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetRebuildEnabled() bool {
	if o == nil || IsNil(o.RebuildEnabled) {
		var ret bool
		return ret
	}
	return *o.RebuildEnabled
}

// GetRebuildEnabledOk returns a tuple with the RebuildEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetRebuildEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.RebuildEnabled) {
		return nil, false
	}
	return o.RebuildEnabled, true
}

// HasRebuildEnabled returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasRebuildEnabled() bool {
	if o != nil && !IsNil(o.RebuildEnabled) {
		return true
	}

	return false
}

// SetRebuildEnabled gets a reference to the given bool and assigns it to the RebuildEnabled field.
func (o *StoragePoolParamGen2) SetRebuildEnabled(v bool) {
	o.RebuildEnabled = &v
}

// GetRebalanceEnabled returns the RebalanceEnabled field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetRebalanceEnabled() bool {
	if o == nil || IsNil(o.RebalanceEnabled) {
		var ret bool
		return ret
	}
	return *o.RebalanceEnabled
}

// GetRebalanceEnabledOk returns a tuple with the RebalanceEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetRebalanceEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.RebalanceEnabled) {
		return nil, false
	}
	return o.RebalanceEnabled, true
}

// HasRebalanceEnabled returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasRebalanceEnabled() bool {
	if o != nil && !IsNil(o.RebalanceEnabled) {
		return true
	}

	return false
}

// SetRebalanceEnabled gets a reference to the given bool and assigns it to the RebalanceEnabled field.
func (o *StoragePoolParamGen2) SetRebalanceEnabled(v bool) {
	o.RebalanceEnabled = &v
}

// GetZeroPaddingEnabled returns the ZeroPaddingEnabled field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetZeroPaddingEnabled() string {
	if o == nil || IsNil(o.ZeroPaddingEnabled) {
		var ret string
		return ret
	}
	return *o.ZeroPaddingEnabled
}

// GetZeroPaddingEnabledOk returns a tuple with the ZeroPaddingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetZeroPaddingEnabledOk() (*string, bool) {
	if o == nil || IsNil(o.ZeroPaddingEnabled) {
		return nil, false
	}
	return o.ZeroPaddingEnabled, true
}

// HasZeroPaddingEnabled returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasZeroPaddingEnabled() bool {
	if o != nil && !IsNil(o.ZeroPaddingEnabled) {
		return true
	}

	return false
}

// SetZeroPaddingEnabled gets a reference to the given string and assigns it to the ZeroPaddingEnabled field.
func (o *StoragePoolParamGen2) SetZeroPaddingEnabled(v string) {
	o.ZeroPaddingEnabled = &v
}

// GetUseRmcache returns the UseRmcache field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetUseRmcache() string {
	if o == nil || IsNil(o.UseRmcache) {
		var ret string
		return ret
	}
	return *o.UseRmcache
}

// GetUseRmcacheOk returns a tuple with the UseRmcache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetUseRmcacheOk() (*string, bool) {
	if o == nil || IsNil(o.UseRmcache) {
		return nil, false
	}
	return o.UseRmcache, true
}

// HasUseRmcache returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasUseRmcache() bool {
	if o != nil && !IsNil(o.UseRmcache) {
		return true
	}

	return false
}

// SetUseRmcache gets a reference to the given string and assigns it to the UseRmcache field.
func (o *StoragePoolParamGen2) SetUseRmcache(v string) {
	o.UseRmcache = &v
}

// GetUseRfcache returns the UseRfcache field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetUseRfcache() string {
	if o == nil || IsNil(o.UseRfcache) {
		var ret string
		return ret
	}
	return *o.UseRfcache
}

// GetUseRfcacheOk returns a tuple with the UseRfcache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetUseRfcacheOk() (*string, bool) {
	if o == nil || IsNil(o.UseRfcache) {
		return nil, false
	}
	return o.UseRfcache, true
}

// HasUseRfcache returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasUseRfcache() bool {
	if o != nil && !IsNil(o.UseRfcache) {
		return true
	}

	return false
}

// SetUseRfcache gets a reference to the given string and assigns it to the UseRfcache field.
func (o *StoragePoolParamGen2) SetUseRfcache(v string) {
	o.UseRfcache = &v
}

// GetRmcacheWriteHandlingMode returns the RmcacheWriteHandlingMode field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetRmcacheWriteHandlingMode() string {
	if o == nil || IsNil(o.RmcacheWriteHandlingMode) {
		var ret string
		return ret
	}
	return *o.RmcacheWriteHandlingMode
}

// GetRmcacheWriteHandlingModeOk returns a tuple with the RmcacheWriteHandlingMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetRmcacheWriteHandlingModeOk() (*string, bool) {
	if o == nil || IsNil(o.RmcacheWriteHandlingMode) {
		return nil, false
	}
	return o.RmcacheWriteHandlingMode, true
}

// HasRmcacheWriteHandlingMode returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasRmcacheWriteHandlingMode() bool {
	if o != nil && !IsNil(o.RmcacheWriteHandlingMode) {
		return true
	}

	return false
}

// SetRmcacheWriteHandlingMode gets a reference to the given string and assigns it to the RmcacheWriteHandlingMode field.
func (o *StoragePoolParamGen2) SetRmcacheWriteHandlingMode(v string) {
	o.RmcacheWriteHandlingMode = &v
}

// GetErasureCodingPolicy returns the ErasureCodingPolicy field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetErasureCodingPolicy() string {
	if o == nil || IsNil(o.ErasureCodingPolicy) {
		var ret string
		return ret
	}
	return *o.ErasureCodingPolicy
}

// GetErasureCodingPolicyOk returns a tuple with the ErasureCodingPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetErasureCodingPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.ErasureCodingPolicy) {
		return nil, false
	}
	return o.ErasureCodingPolicy, true
}

// HasErasureCodingPolicy returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasErasureCodingPolicy() bool {
	if o != nil && !IsNil(o.ErasureCodingPolicy) {
		return true
	}

	return false
}

// SetErasureCodingPolicy gets a reference to the given string and assigns it to the ErasureCodingPolicy field.
func (o *StoragePoolParamGen2) SetErasureCodingPolicy(v string) {
	o.ErasureCodingPolicy = &v
}

// GetNumDataBlocks returns the NumDataBlocks field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetNumDataBlocks() int32 {
	if o == nil || IsNil(o.NumDataBlocks) {
		var ret int32
		return ret
	}
	return *o.NumDataBlocks
}

// GetNumDataBlocksOk returns a tuple with the NumDataBlocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetNumDataBlocksOk() (*int32, bool) {
	if o == nil || IsNil(o.NumDataBlocks) {
		return nil, false
	}
	return o.NumDataBlocks, true
}

// HasNumDataBlocks returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasNumDataBlocks() bool {
	if o != nil && !IsNil(o.NumDataBlocks) {
		return true
	}

	return false
}

// SetNumDataBlocks gets a reference to the given int32 and assigns it to the NumDataBlocks field.
func (o *StoragePoolParamGen2) SetNumDataBlocks(v int32) {
	o.NumDataBlocks = &v
}

// GetNumParityBlocks returns the NumParityBlocks field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetNumParityBlocks() int32 {
	if o == nil || IsNil(o.NumParityBlocks) {
		var ret int32
		return ret
	}
	return *o.NumParityBlocks
}

// GetNumParityBlocksOk returns a tuple with the NumParityBlocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetNumParityBlocksOk() (*int32, bool) {
	if o == nil || IsNil(o.NumParityBlocks) {
		return nil, false
	}
	return o.NumParityBlocks, true
}

// HasNumParityBlocks returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasNumParityBlocks() bool {
	if o != nil && !IsNil(o.NumParityBlocks) {
		return true
	}

	return false
}

// SetNumParityBlocks gets a reference to the given int32 and assigns it to the NumParityBlocks field.
func (o *StoragePoolParamGen2) SetNumParityBlocks(v int32) {
	o.NumParityBlocks = &v
}

// GetProtectionScheme returns the ProtectionScheme field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetProtectionScheme() string {
	if o == nil || IsNil(o.ProtectionScheme) {
		var ret string
		return ret
	}
	return *o.ProtectionScheme
}

// GetProtectionSchemeOk returns a tuple with the ProtectionScheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetProtectionSchemeOk() (*string, bool) {
	if o == nil || IsNil(o.ProtectionScheme) {
		return nil, false
	}
	return o.ProtectionScheme, true
}

// HasProtectionScheme returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasProtectionScheme() bool {
	if o != nil && !IsNil(o.ProtectionScheme) {
		return true
	}

	return false
}

// SetProtectionScheme gets a reference to the given string and assigns it to the ProtectionScheme field.
func (o *StoragePoolParamGen2) SetProtectionScheme(v string) {
	o.ProtectionScheme = &v
}

// GetCompressionMethod returns the CompressionMethod field value if set, zero value otherwise.
func (o *StoragePoolParamGen2) GetCompressionMethod() string {
	if o == nil || IsNil(o.CompressionMethod) {
		var ret string
		return ret
	}
	return *o.CompressionMethod
}

// GetCompressionMethodOk returns a tuple with the CompressionMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoragePoolParamGen2) GetCompressionMethodOk() (*string, bool) {
	if o == nil || IsNil(o.CompressionMethod) {
		return nil, false
	}
	return o.CompressionMethod, true
}

// HasCompressionMethod returns a boolean if a field has been set.
func (o *StoragePoolParamGen2) HasCompressionMethod() bool {
	if o != nil && !IsNil(o.CompressionMethod) {
		return true
	}

	return false
}

// SetCompressionMethod gets a reference to the given string and assigns it to the CompressionMethod field.
func (o *StoragePoolParamGen2) SetCompressionMethod(v string) {
	o.CompressionMethod = &v
}

func (o StoragePoolParamGen2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoragePoolParamGen2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["protectionDomainId"] = o.ProtectionDomainId
	if !IsNil(o.MediaType) {
		toSerialize["mediaType"] = o.MediaType
	}
	if !IsNil(o.SparePercentage) {
		toSerialize["sparePercentage"] = o.SparePercentage
	}
	if !IsNil(o.RebuildEnabled) {
		toSerialize["rebuildEnabled"] = o.RebuildEnabled
	}
	if !IsNil(o.RebalanceEnabled) {
		toSerialize["rebalanceEnabled"] = o.RebalanceEnabled
	}
	if !IsNil(o.ZeroPaddingEnabled) {
		toSerialize["zeroPaddingEnabled"] = o.ZeroPaddingEnabled
	}
	if !IsNil(o.UseRmcache) {
		toSerialize["useRmcache"] = o.UseRmcache
	}
	if !IsNil(o.UseRfcache) {
		toSerialize["useRfcache"] = o.UseRfcache
	}
	if !IsNil(o.RmcacheWriteHandlingMode) {
		toSerialize["rmcacheWriteHandlingMode"] = o.RmcacheWriteHandlingMode
	}
	if !IsNil(o.ErasureCodingPolicy) {
		toSerialize["erasureCodingPolicy"] = o.ErasureCodingPolicy
	}
	if !IsNil(o.NumDataBlocks) {
		toSerialize["numDataBlocks"] = o.NumDataBlocks
	}
	if !IsNil(o.NumParityBlocks) {
		toSerialize["numParityBlocks"] = o.NumParityBlocks
	}
	if !IsNil(o.ProtectionScheme) {
		toSerialize["protectionScheme"] = o.ProtectionScheme
	}
	if !IsNil(o.CompressionMethod) {
		toSerialize["compressionMethod"] = o.CompressionMethod
	}
	return toSerialize, nil
}

func (o *StoragePoolParamGen2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"protectionDomainId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoragePoolParamGen2 := _StoragePoolParamGen2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoragePoolParamGen2)

	if err != nil {
		return err
	}

	*o = StoragePoolParamGen2(varStoragePoolParamGen2)

	return err
}

type NullableStoragePoolParamGen2 struct {
	value *StoragePoolParamGen2
	isSet bool
}

func (v NullableStoragePoolParamGen2) Get() *StoragePoolParamGen2 {
	return v.value
}

func (v *NullableStoragePoolParamGen2) Set(val *StoragePoolParamGen2) {
	v.value = val
	v.isSet = true
}

func (v NullableStoragePoolParamGen2) IsSet() bool {
	return v.isSet
}

func (v *NullableStoragePoolParamGen2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoragePoolParamGen2(val *StoragePoolParamGen2) *NullableStoragePoolParamGen2 {
	return &NullableStoragePoolParamGen2{value: val, isSet: true}
}

func (v NullableStoragePoolParamGen2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoragePoolParamGen2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
