/*
PowerFlex 5.x Gen2 REST API

OpenAPI specification for PowerFlex 5.x Gen2 REST API endpoints implemented in goscaleio SDK

API version: 5.1.0
Contact: ansible.team@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SetDeviceCapacityLimitGen2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDeviceCapacityLimitGen2{}

// SetDeviceCapacityLimitGen2 struct for SetDeviceCapacityLimitGen2
type SetDeviceCapacityLimitGen2 struct {
	// Capacity limit in KB
	CapacityLimitInKb string `json:"capacityLimitInKb"`
}

type _SetDeviceCapacityLimitGen2 SetDeviceCapacityLimitGen2

// NewSetDeviceCapacityLimitGen2 instantiates a new SetDeviceCapacityLimitGen2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDeviceCapacityLimitGen2(capacityLimitInKb string) *SetDeviceCapacityLimitGen2 {
	this := SetDeviceCapacityLimitGen2{}
	this.CapacityLimitInKb = capacityLimitInKb
	return &this
}

// NewSetDeviceCapacityLimitGen2WithDefaults instantiates a new SetDeviceCapacityLimitGen2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDeviceCapacityLimitGen2WithDefaults() *SetDeviceCapacityLimitGen2 {
	this := SetDeviceCapacityLimitGen2{}
	return &this
}

// GetCapacityLimitInKb returns the CapacityLimitInKb field value
func (o *SetDeviceCapacityLimitGen2) GetCapacityLimitInKb() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CapacityLimitInKb
}

// GetCapacityLimitInKbOk returns a tuple with the CapacityLimitInKb field value
// and a boolean to check if the value has been set.
func (o *SetDeviceCapacityLimitGen2) GetCapacityLimitInKbOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityLimitInKb, true
}

// SetCapacityLimitInKb sets field value
func (o *SetDeviceCapacityLimitGen2) SetCapacityLimitInKb(v string) {
	o.CapacityLimitInKb = v
}

func (o SetDeviceCapacityLimitGen2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDeviceCapacityLimitGen2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capacityLimitInKb"] = o.CapacityLimitInKb
	return toSerialize, nil
}

func (o *SetDeviceCapacityLimitGen2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capacityLimitInKb",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDeviceCapacityLimitGen2 := _SetDeviceCapacityLimitGen2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetDeviceCapacityLimitGen2)

	if err != nil {
		return err
	}

	*o = SetDeviceCapacityLimitGen2(varSetDeviceCapacityLimitGen2)

	return err
}

type NullableSetDeviceCapacityLimitGen2 struct {
	value *SetDeviceCapacityLimitGen2
	isSet bool
}

func (v NullableSetDeviceCapacityLimitGen2) Get() *SetDeviceCapacityLimitGen2 {
	return v.value
}

func (v *NullableSetDeviceCapacityLimitGen2) Set(val *SetDeviceCapacityLimitGen2) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDeviceCapacityLimitGen2) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDeviceCapacityLimitGen2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDeviceCapacityLimitGen2(val *SetDeviceCapacityLimitGen2) *NullableSetDeviceCapacityLimitGen2 {
	return &NullableSetDeviceCapacityLimitGen2{value: val, isSet: true}
}

func (v NullableSetDeviceCapacityLimitGen2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDeviceCapacityLimitGen2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
