# Controls when the workflow will run
on:
  push:
    branches: [ "test-auto-docs" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout-powerflex:
    name: Check out to powerflex repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: test-auto-docs
          path: powerflex
      - name: Check out to docs repo
        uses: actions/checkout@v3
        with:
          repository: dell/terraform-docs
          token: ${{ secrets.SERVICE_TOKEN }}    
          ref: test-docs-automation
          path: docs
      - name: Set up Git
        run: |
          cd docs/
          git config --local user.email "anika.agiwal@dell.com"
          git config --local user.name "AnikaAgiwal2711"
      - name: Make changes
        run: |
          cd docs/ && make powerflex
      - name: Commit changes
        run: |
          cd docs/
          git add .
          git commit -m "push the docs generated from powerflex to docs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: dell/terraform-docs 
          github_token: ${{ secrets.SERVICE_TOKEN }}
          directory: docs
          branch: test-docs-automation     
