# Controls when the workflow will run
on:
  push:
    branches: [ "test-auto-docs" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout-powerflex:
    name: Check out to powerflex repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: test-auto-docs
          path: powerflex
      - run: ls -ltr 
      - run: pwd
      - name: Check out to docs repo
        uses: actions/checkout@v3
        with:
          repository: dell/terraform-docs
          token: ${{ secrets.SERVICE_TOKEN }}    
          ref: test-docs-automation
          path: docs
      - run: ls -ltr
      - run: pwd
      - run: cd ../ && ls -a
      - run: cd docs/
      - run: make powerflex
      - run: git status     
